"""Per-topic accuracy for the lenient per-language XGBoost grid.

The worker runs stored per-tag F1 but not per-tag accuracy. This script reads,
for each (language, mode), the Optuna-best params + the in-sample tuned
thresholds from `xgboost_perlang_lenient_{lang}.json`, retrains the models
deterministically (same seed / params / max_bin / 2 threads as the workers),
and reports per-tag accuracy on devtest and test.

Sanity check: the recomputed per-tag F1 must match the stored per-tag F1
(otherwise the numbers are not the same models). Max abs diff is reported.

Outputs: xgboost_perlang_lenient_pertopic.md / .json (rewritten after each cell).
Usage: python pertopic_accuracy.py [--langs en,it,de,fr] [--modes mean,bos,eos,lead] [--outdir .]
"""
import argparse
import json
import os
import time

os.environ["OMP_NUM_THREADS"] = "2"
os.environ["MKL_NUM_THREADS"] = "2"
os.environ["OPENBLAS_NUM_THREADS"] = "2"

import numpy as np
from sklearn.metrics import f1_score

import xgboost_topic_optuna as X


def fmt(v):
    return f"{v:.3f}"


def write_md(res, outdir):
    langs = [l for l in X.LANGS if any(l in res["splits"]["test"].get(m, {}) for m in X.MODES)]
    modes = [m for m in X.MODES if any(l in res["splits"]["test"].get(m, {}) for l in langs)]
    if not langs:
        return
    lines = []
    lines.append("# XGBoost topic classifier — per-topic accuracy (lenient labels, tuned thresholds)\n")
    lines.append("Generated by `pertopic_accuracy.py`. For every (language, pooling) cell the Optuna-best "
                 "params stored in `xgboost_perlang_lenient_{lang}.json` are retrained deterministically "
                 "(seed 0, `tree_method=hist`, `max_bin=64`, 2 threads — the exact worker configuration) "
                 "on dev (for devtest) and dev+devtest (for test); the stored in-sample per-tag tuned "
                 "thresholds are applied. **Accuracy = per-tag binary agreement** on the split; note that "
                 "for rare tags it is dominated by true negatives — per-tag F1 for the same models is in "
                 "the JSONs / per-mode tables.\n")
    # reproduction check summary
    diffs = [v2[k] for m in res["reproduction"].values() for v2 in m.values() for k, v3 in v2.items()]
    max_diff = max((d for d in diffs), default=0.0)
    lines.append(f"Reproduction check: max |recomputed − stored| per-tag F1 over all cells = {max_diff:.2e} "
                 "(0 ⇒ identical models).\n")

    def table(split, header_npos=False):
        out = []
        for lang in langs:
            have = [m for m in X.MODES if lang in res["splits"][split].get(m, {})]
            if not have:
                continue
            out.append(f"### {lang}\n")
            cols = (["n_pos"] if header_npos else []) + have
            out.append("| topic | " + " | ".join(cols) + " |")
            out.append("|---|" + "---:|" * len(cols))
            for j, tag in enumerate(X.TAGS):
                cells = ([str(int(res["n_pos"][tag]))] if header_npos else []) + \
                        [fmt(res["splits"][split][m][lang]["accuracy"][j]) for m in have]
                out.append(f"| {tag} | " + " | ".join(cells) + " |")
            out.append("")
        return out

    lines.append("## Test (506) — accuracy per topic, rows = topic, columns = pooling mode\n")
    lines.extend(table("test", header_npos=True))
    lines.append("## Cross-language, `mean` mode — accuracy per topic (test)\n")
    lines.append("| topic | n_pos (test) | en | it | de | fr |")
    lines.append("|---|---:|---:|---:|---:|---:|")
    for j, tag in enumerate(X.TAGS):
        cells = []
        for lang in X.LANGS:
            split = res["splits"]["test"].get("mean", {})
            cells.append(fmt(split[lang]["accuracy"][j]) if lang in split else "—")
        lines.append(f"| {tag} | {int(res['n_pos'][tag])} | " + " | ".join(cells) + " |")
    lines.append("")
    lines.append("## Devtest (506) — accuracy per topic (for the dev-trained models)\n")
    lines.extend(table("devtest"))
    lines.append("## Reproduction check (per cell)\n")
    lines.append("| mode | language | max abs F1 diff (devtest) | max abs F1 diff (test) |")
    lines.append("|---|---|---:|---:|")
    for mode in modes:
        for lang in langs:
            r = res["reproduction"].get(mode, {}).get(lang)
            if r:
                lines.append(f"| {mode} | {lang} | {r['devtest_max_abs_f1_diff']:.2e} | "
                             f"{r['test_max_abs_f1_diff']:.2e} |")
    lines.append("")
    with open(os.path.join(outdir, "xgboost_perlang_lenient_pertopic.md"), "w", encoding="utf-8") as f:
        f.write("\n".join(lines))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--langs", default="en,it,de,fr")
    ap.add_argument("--modes", default="mean,bos,eos,lead")
    ap.add_argument("--outdir", default=".")
    args = ap.parse_args()
    langs = [s for s in args.langs.split(",") if s in X.LANGS]
    modes = [s for s in args.modes.split(",") if s in X.MODES]
    outdir = args.outdir

    t0 = time.time()
    df, Y, masks, counts = X.load_data("lenient")
    res = {
        "generated": time.strftime("%Y-%m-%d %H:%M:%S"),
        "note": "best params + tuned thresholds read from xgboost_perlang_lenient_{lang}.json; "
                "models retrained deterministically to recover per-tag accuracy",
        "n_pos": {tag: int(counts["test"][j]) for j, tag in enumerate(X.TAGS)},
        "n_pos_all": {tag: int(counts["all"][j]) for j, tag in enumerate(X.TAGS)},
        "splits": {"devtest": {}, "test": {}},
        "reproduction": {},
    }
    for mode in modes:
        for lang in langs:
            path = os.path.join(outdir, f"xgboost_perlang_lenient_{lang}.json")
            if not os.path.exists(path):
                print(f"[pertopic] missing {path}; skip", flush=True)
                continue
            with open(path, encoding="utf-8") as f:
                j = json.load(f)
            if mode not in j["modes"]:
                print(f"[pertopic] {lang}: mode {mode} absent; skip", flush=True)
                continue
            mr = j["modes"][mode]
            params = mr["tuned"]["best_params"]
            th_dt = np.array(mr["tuned"]["tuned"]["thresholds"]["devtest"], dtype=float)
            th_te = np.array(mr["tuned"]["tuned"]["thresholds"]["test"], dtype=float)
            Xf = X.load_one_embedding(mode, lang)
            t = time.time()

            # dev-trained model -> devtest
            _, (probs_dt,), _ = X.fit_predict_with_train(
                params, Xf[masks["dev"]], Y[masks["dev"]], [Xf[masks["devtest"]]])
            pred_dt = (probs_dt >= th_dt).astype(int)
            acc_dt = (pred_dt == Y[masks["devtest"]]).mean(axis=0)
            f1_dt = f1_score(Y[masks["devtest"]], pred_dt, average=None, zero_division=0)

            # dev+devtest-trained model -> test
            _, (probs_te,), _ = X.fit_predict_with_train(
                params, Xf[masks["dev_devtest"]], Y[masks["dev_devtest"]], [Xf[masks["test"]]])
            pred_te = (probs_te >= th_te).astype(int)
            acc_te = (pred_te == Y[masks["test"]]).mean(axis=0)
            f1_te = f1_score(Y[masks["test"]], pred_te, average=None, zero_division=0)

            stored_dt = np.array(mr["tuned"]["tuned"]["devtest"]["per_tag"])
            stored_te = np.array(mr["tuned"]["tuned"]["test"]["per_tag"])
            d_dt = float(np.abs(f1_dt - stored_dt).max())
            d_te = float(np.abs(f1_te - stored_te).max())
            print(f"[pertopic] {lang}/{mode}: {time.time() - t:.1f}s | f1-diff dt={d_dt:.2e} te={d_te:.2e}",
                  flush=True)
            res["splits"]["devtest"].setdefault(mode, {})[lang] = {
                "accuracy": np.round(acc_dt, 6).tolist(),
                "f1": np.round(f1_dt, 6).tolist(),
                "thresholds": th_dt.tolist(),
            }
            res["splits"]["test"].setdefault(mode, {})[lang] = {
                "accuracy": np.round(acc_te, 6).tolist(),
                "f1": np.round(f1_te, 6).tolist(),
                "thresholds": th_te.tolist(),
            }
            res["reproduction"].setdefault(mode, {})[lang] = {
                "devtest_max_abs_f1_diff": d_dt,
                "test_max_abs_f1_diff": d_te,
            }
            write_md(res, outdir)
            with open(os.path.join(outdir, "xgboost_perlang_lenient_pertopic.json"), "w",
                      encoding="utf-8") as f:
                json.dump(res, f, indent=2)
    print(f"[pertopic] all done in {time.time() - t0:.1f}s", flush=True)


if __name__ == "__main__":
    main()
