"""Per-topic accuracy for the ENGLISH -> {it,de,fr} transfer models (lenient labels).

For each pooling mode this reads the Optuna-best params from
`xgboost_topic_results_lenient_{mode}.md` (cross-checked against the trials
CSV), retrains the 8 English tag models on all 2009 English rows, re-tunes the
transfer thresholds in-sample (identical protocol: grid 0.05..0.95 on the
all-2009 English predictions), and computes per-tag accuracy for
en (in-sample), it raw / it+D, de raw / de+D, fr raw / fr+D.

Checks: recomputed thresholds and per-tag F1 must match the values stored in
the per-mode md (tuned transfer table); max abs diffs are reported.

Outputs: xgboost_pertopic_transfer.md / .json (rewritten after each mode).
Usage: python pertopic_accuracy_transfer.py [--modes mean,bos,eos,lead] [--outdir .]
"""
import argparse
import json
import os
import time

os.environ["OMP_NUM_THREADS"] = "2"
os.environ["MKL_NUM_THREADS"] = "2"
os.environ["OPENBLAS_NUM_THREADS"] = "2"

import numpy as np
from sklearn.metrics import f1_score

import xgboost_topic_optuna as X


def fmt(v):
    return f"{v:.3f}"


def parse_best_params(md_text):
    """Parse the 'Best Optuna parameters' code block -> (params dict, best trial)."""
    try:
        block = md_text.split("Best Optuna parameters", 1)[1].split("```")[1]
    except IndexError:
        return None, None
    params, trial = {}, None
    for line in block.strip().splitlines():
        if ":" not in line:
            continue
        k, v = line.split(":", 1)
        k, v = k.strip(), v.strip()
        if k.startswith("best trial"):
            trial = int(v)
        elif k.startswith("best value"):
            continue
        else:
            try:
                params[k] = float(v)
            except ValueError:
                pass
    for k in ("max_depth", "n_estimators", "min_child_weight"):
        if k in params:
            params[k] = int(params[k])
    return params, trial


def parse_md_table(md_text, heading):
    """Parse a markdown table under `heading` -> list of cell lists."""
    i = md_text.find(heading)
    if i < 0:
        return []
    rows = []
    for line in md_text[i:].splitlines():
        line = line.strip()
        if not line.startswith("|"):
            if rows:
                break
            continue
        cells = [c.strip() for c in line.strip("|").split("|")]
        if not cells or cells[0] == "tag" or cells[0] == "test set" or set(cells[0]) <= set("-: "):
            continue
        rows.append(cells)
    return rows


def write_md(res, outdir):
    modes = [m for m in X.MODES if m in res["modes"]]
    lines = []
    lines.append("# XGBoost topic classifier — per-topic accuracy of the English→other-language transfer (lenient labels)\n")
    lines.append("Generated by `pertopic_accuracy_transfer.py`. For every pooling mode the Optuna-best params "
                 "(stored in `xgboost_topic_results_lenient_{mode}.md`) are retrained deterministically on all "
                 "2009 **English** rows (seed 0, hist, max_bin=64, 2 threads); transfer thresholds are tuned "
                 "in-sample on the all-2009 English predictions (grid 0.05..0.95, per-tag F1); shifted features "
                 "are `emb_L + D_L` with `D_L = mean(emb_en − emb_L)`. Evaluation is over all 2009 rows. "
                 "**Accuracy = per-tag binary agreement** (TN-dominated for rare tags; F1 is in the JSON).\n")
    diff_th = max((v["threshold_max_abs_diff"] for m in res["modes"].values() for v in m["rows"].values()), default=0.0)
    diff_f1 = max((v["f1_max_abs_diff"] for m in res["modes"].values() for v in m["rows"].values()), default=0.0)
    lines.append(f"Reproduction check: max |recomputed − stored| thresholds = {diff_th:.2e}, "
                 f"per-tag F1 = {diff_f1:.2e} (0 ⇒ identical models).\n")
    for name in res["row_order"]:
        lines.append(f"## {name}\n")
        lines.append("| topic | " + " | ".join(modes) + " |")
        lines.append("|---|" + "---:|" * len(modes))
        for j, tag in enumerate(X.TAGS):
            cells = [fmt(res["modes"][m]["rows"][name]["accuracy"][j]) if name in res["modes"][m]["rows"] else "—"
                     for m in modes]
            lines.append(f"| {tag} | " + " | ".join(cells) + " |")
        lines.append("")
    lines.append("## Gain of +D (Δaccuracy, +D − raw) per topic\n")
    for lang in ("it", "de", "fr"):
        lines.append(f"### {lang}\n")
        lines.append("| topic | " + " | ".join(modes) + " |")
        lines.append("|---|" + "---:|" * len(modes))
        for j, tag in enumerate(X.TAGS):
            cells = []
            for m in modes:
                rows_m = res["modes"][m]["rows"]
                raw, dp = f"{lang} raw", f"{lang}+D"
                if raw in rows_m and dp in rows_m:
                    g = rows_m[dp]["accuracy"][j] - rows_m[raw]["accuracy"][j]
                    cells.append(f"{g:+.4f}")
                else:
                    cells.append("—")
            lines.append(f"| {tag} | " + " | ".join(cells) + " |")
        lines.append("")
    with open(os.path.join(outdir, "xgboost_pertopic_transfer.md"), "w", encoding="utf-8") as f:
        f.write("\n".join(lines))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--modes", default="mean,bos,eos,lead")
    ap.add_argument("--outdir", default=".")
    args = ap.parse_args()
    modes = [s for s in args.modes.split(",") if s in X.MODES]
    outdir = args.outdir

    t0 = time.time()
    df, Y, masks, counts = X.load_data("lenient")
    n_rows = len(Y)
    res = {
        "generated": time.strftime("%Y-%m-%d %H:%M:%S"),
        "note": "English models trained on all 2009 rows; accuracy with in-sample-tuned transfer thresholds",
        "n_pos": {tag: int(counts["all"][j]) for j, tag in enumerate(X.TAGS)},
        "row_order": ["en (in-sample)"] + [f"{l}{s}" for l in ("it", "de", "fr") for s in (" raw", "+D")],
        "modes": {},
    }
    for mode in modes:
        md_path = os.path.join(outdir, f"xgboost_topic_results_lenient_{mode}.md")
        if not os.path.exists(md_path):
            print(f"[transfer-pertopic] missing {md_path}; skip", flush=True)
            continue
        md_text = open(md_path, encoding="utf-8").read()
        params, best_trial = parse_best_params(md_text)
        if params is None:
            print(f"[transfer-pertopic] {mode}: no params block; skip", flush=True)
            continue
        # cross-check best params against the trials csv
        csv_path = os.path.join(outdir, f"xgboost_optuna_trials_lenient_{mode}.csv")
        if os.path.exists(csv_path):
            import pandas as pd
            tr = pd.read_csv(csv_path)
            idx = tr["value_macro_f1"].idxmax()
            for k in params:
                if k in tr.columns:
                    v_csv = tr.loc[idx, k]
                    v_md = params[k]
                    if abs(float(v_csv) - float(v_md)) > 1e-9 * max(1.0, abs(v_md)):
                        print(f"[transfer-pertopic] {mode}: param {k} md={v_md} csv={v_csv} differ", flush=True)
            print(f"[transfer-pertopic] {mode}: best trial md={best_trial} csv={int(tr.loc[idx, 'trial'])}",
                  flush=True)

        Xd = X.load_mode_embeddings(mode)
        t = time.time()
        models, train_probs = [], np.zeros((n_rows, len(X.TAGS)))
        for j in range(len(X.TAGS)):
            model = X.xgb.XGBClassifier(**X.make_params(params))
            model.fit(Xd["en"], Y[:, j])
            models.append(model)
            train_probs[:, j] = model.predict_proba(Xd["en"])[:, 1]
        th = X.tune_thresholds(Y, train_probs)

        # stored thresholds check (md 'Per-tag tuned thresholds' table, all-2009 column)
        thr_rows = parse_md_table(md_text, "Per-tag tuned thresholds")
        stored_th = None
        if len(thr_rows) == len(X.TAGS):
            stored_th = np.array([float(r[2]) for r in thr_rows])
        diff_th = float(np.abs(th - stored_th).max()) if stored_th is not None else float("nan")

        # stored tuned-transfer F1 check
        f1_rows = parse_md_table(md_text, "### Tuned thresholds")
        stored_f1 = {}
        for r in f1_rows:
            if len(r) >= 12:
                stored_f1[r[0]] = [float(x) for x in r[4:12]]

        shifts = {l: (Xd["en"] - Xd[l]).mean(axis=0) for l in ("it", "de", "fr")}
        evals = [("en (in-sample)", Xd["en"])]
        for l in ("it", "de", "fr"):
            evals.append((f"{l} raw", Xd[l]))
            evals.append((f"{l}+D", Xd[l] + shifts[l]))

        rows = {}
        for name, Xt in evals:
            probs = np.column_stack([m.predict_proba(Xt)[:, 1] for m in models])
            pred = (probs >= th[None, :]).astype(int)
            acc = (pred == Y).mean(axis=0)
            f1 = f1_score(Y, pred, average=None, zero_division=0)
            d = float(np.abs(f1 - np.array(stored_f1[name])).max()) if name in stored_f1 else float("nan")
            rows[name] = {"accuracy": np.round(acc, 6).tolist(), "f1": np.round(f1, 6).tolist(),
                          "f1_max_abs_diff": d}
        for name in rows:
            rows[name]["threshold_max_abs_diff"] = diff_th
        res["modes"][mode] = {"params": params, "best_trial": best_trial,
                              "transfer_thresholds": th.tolist(), "rows": rows}
        acc_te = rows["fr raw"]["accuracy"]
        print(f"[transfer-pertopic] {mode}: done in {time.time() - t:.1f}s | "
              f"thr-diff={diff_th:.2e} f1-diff={max(r['f1_max_abs_diff'] for r in rows.values()):.2e} | "
              f"fr raw mean-mode acc t/s/c/p/h/g/sc/sf = " + " ".join(f"{a:.2f}" for a in acc_te), flush=True)
        write_md(res, outdir)
        with open(os.path.join(outdir, "xgboost_pertopic_transfer.json"), "w", encoding="utf-8") as f:
            json.dump(res, f, indent=2)
    print(f"[transfer-pertopic] all done in {time.time() - t0:.1f}s", flush=True)


if __name__ == "__main__":
    main()
